# SEGUNDA LISTA DE EXERCÍCIOS

1. Crie uma função para calcular as quatro operações matemáticas (soma, subtração, divisão e multiplicação) sendo fornecidos 2 números e informando o resultado de cada operação.

In [18]:
def operacoes(numero1, numero2):
    soma= numero1 + numero2
    subt = numero1 - numero2
    mult = numero1 * numero2
    if numero2 != 0:
        divi = numero1 / numero2
    else:
        divi = 'Divisão por zero não permitida'

    return soma, subt, mult, divi


numero1 = int(input("Informe o primeiro número: "))
numero2 = int(input("Informe o segundo número: "))

print(
    f'A soma é: {operacoes(numero1, numero2)[0]}\n'
    f'A subtração é: {operacoes(numero1, numero2)[1]}\n'
    f'A multiplicação é {operacoes(numero1, numero2)[2]}\n'
    f'A divisão é: {operacoes(numero1,numero2)[3]}'
)


A soma é: 48
A subtração é: 32
A multiplicação é 320
A divisão é: 5.0


2. Criar uma função para retornar se um número é par ou ímpar


In [12]:
def paridade(numero):
    if numero % 2 == 0:
        print(f'O número {numero} é par')
    else:
        print(f'O número {numero} é ímpar.')

numero = int(input("Digite um número: "))

paridade(numero)


O número 455 é ímpar.


3. Faça um programa que tenha uma função chamada maior, que receba vários parâmetros com valores inteiros. Seu programa tem que analisar todos os valores e dizer qual deles é maior.


In [14]:
def maior(*numeros):
    if len(numeros) == 0:
        print("Nenhum número foi fornecido.")
        return
    maior_numero = max(numeros)
    print(f"O maior número fornecido foi: {maior_numero}")

numeros = input("Digite os números separados por espaço: ").split()
numeros = [int(numero) for numero in numeros]

maior(*numeros)


O maior número fornecido foi: 21


4. Faça um programa que tenha uma função chamada area(), que receba as dimensões de um terreno retangular (largura e comprimento) e mostre a área do terreno.


In [21]:
def area(largura, comprimento):
    area_terreno = largura * comprimento
    print(f'A área do terreno é {area_terreno:.2f}m²')

largura = float(input("Informe a largura em metros: "))
comprimento = float(input("Informe o comprimento em metros: "))

area(largura, comprimento)
    
    

A área do terreno é 2475.00m²


5. Faça uma função que informe a quantidade de dígitos de um determinado número inteiro informado pelo usuário.


In [3]:
def tamanho(inteiro):
    return len(str(inteiro))

inteiro = int(input("Informe um número inteiro: "))

print(f'O número {inteiro} tem {tamanho(inteiro)} dígitos')


O número 45656841 tem 8 dígitos


6. Faça um função chamada somaImposto. A função possui dois parâmetros:

a) taxaImposto, que é a porcentagem de imposto sobre vendas.

b) custo, que é o custo de um item antes do imposto.

A função retorna o valor de custo alterado para incluir o imposto sobre vendas.


In [11]:
def somaImposto(taxaImposto, custo):
    valor_imposto = custo * (taxaImposto / 100)
    custo_com_imposto = custo + valor_imposto
    return custo_com_imposto


taxa = float(input('Informe o valor da taxa em %: '))
custo_inicial = float(input('Informe o valor do custo inicial: '))
custo_final = somaImposto(taxa, custo_inicial)
print(f"Custo com imposto: R${custo_final:.2f}")


Custo com imposto: R$1150.00


7. Cruiar uma função para gerar uma matriz 10x10 (array) de forma aleatória.


In [15]:
import numpy as np

def gerar_matriz_aleatoria():
    matriz = np.random.randint(0, 100, size=(10, 10))
    return matriz

matriz = gerar_matriz_aleatoria()
print(matriz)


[[21 72 31 29 66 31 94 26 52 50]
 [97 56 10 58 93 23 54 63 38 23]
 [75 74 48 16 66 52  1 94  0 99]
 [51  2 76 10 32 78 23 67 23 31]
 [83 91 30 44 29 20 47 87 64 98]
 [53 23  8 76 67 16 47 60 69 66]
 [46 15 53 58 59 10 99  9 14 99]
 [68 24 30 19 18 15 64  8 15 69]
 [35 85  8  4 34 56 75 64 13 99]
 [38 97 29 44 31 87 62 68 44 69]]


8. Faça um programa que tenha uma lista pronta chamada números e duas funções chamadas sorteia() e somaPar(). A primeira função vai sortear 5 números da lista e vai colocá-los em outra lista e a segunda função vai mostrar a soma entre todos os valores pares sorteados pela função anterior. (Utilize o import Random e a função sorteados ficará: sorteados = random.sample(lista, 5)).


In [6]:
import random

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

def sorteia():
    sorteados = random.sample(numeros, 5)
    return sorteados

def somaPar(lista):
    soma = sum(num for num in lista if num % 2 == 0)
    return soma

numeros_sorteados = sorteia()
print(f"Números sorteados: {numeros_sorteados}")

soma_pares = somaPar(numeros_sorteados)
print(f"Soma dos números pares sorteados: {soma_pares}")


Números sorteados: [4, 8, 6, 5, 7]
Soma dos números pares sorteados: 18
